### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by lvminia** [4w4k3/BeeLogger#1]
I've installed Parrot OS on virtualbox and when I run BeeLogger, I'm always getting the same error : " winserver: could not save registry branch to user.reg : no space left". 
![screen shot 2017-03-01 at 3 44 43 pm](https://cloud.githubusercontent.com/assets/12136889/23464692/39ea90b4-fe96-11e6-8641-39f8a0eb99e6.png)
![screen shot 2017-03-01 at 3 46 58 pm](https://cloud.githubusercontent.com/assets/12136889/23464752/6b9997f4-fe96-11e6-91b8-73d47e402211.png)
I added 15Go on my virtual machine but it didn't change anything.
Is it because I'm using a virtual machine ? (I'm not able to test it on non-virtual machine right now).

**Comment by 4w4k3** [comment]
Not is because you're using vm, bee need more space 'cause have dependencies like VCForPython, please create new virtual machinw with more space.
