### ISSUE TITLE
 No such file or directory

### ISSUE THREAD

**Issue by adalenv** [4w4k3/BeeLogger#10]
These info above are correct? (y/n) :y
C:\Python27\python.exe: can't open file '/root/.wine/drive_c/Python27/Scripts/pyinstaller-script.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "bee.py", line 184, in <module>
    main()
  File "bee.py", line 139, in main
    os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory

**Comment by 4w4k3** [comment]
Try now

**Comment by tecpatte** [comment]
I have the same problem...

**Comment by 4w4k3** [comment]
Reclone please and try it again

**Comment by 4w4k3** [comment]
Following the video steps

**Comment by sunnyhooda-11** [comment]
bro it doesn't solve the problem

**Comment by el-laco** [comment]
same prob
