### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by hamzeh279** [4w4k3/BeeLogger#11]
sh: 1: wine: not found
Traceback (most recent call last):
  File "bee.py", line 184, in <module>
    main()
  File "bee.py", line 139, in main
    os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory

**Comment by 4w4k3** [comment]
Wait until new version release: 03/26

**Comment by 4w4k3** [comment]
Now its okay try out :D
