### ISSUE TITLE
beelogger please helpppppppppppppp

### ISSUE THREAD

**Issue by owx1234** [4w4k3/BeeLogger#12]
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
wine: cannot find '/root/.wine/drive_c/Python27/python.exe'
Traceback (most recent call last):
  File "bee.py", line 184, in <module>
    main()
  File "bee.py", line 139, in main
    os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory

**Comment by 4w4k3** [comment]
Wait until new version release: 03/26

**Comment by pathibulaire** [comment]
I hope ,you  can post your windows project today .I wait it ,because  i' ve tried to adapt it for pentestbox in windows but i learn python not long time ago .Sorry for my english ,pentestbox is a good things for linux tools on windows. thanks

**Comment by 4w4k3** [comment]
Windows version will need wait more, but linux now are ok
