### ISSUE TITLE
Programm is not installing

### ISSUE THREAD

**Issue by ilko1810** [4w4k3/BeeLogger#13]
Me and my friend cant install the programm. It was working a few weeks ago but now the python part doesnt work. I cant install python. I keep clicking next but it doesnt work. Installing the dependicies give a error message as well. I tried on 2 computers.

**Comment by 4w4k3** [comment]
I'll provide a custom distro with he installed, in some computers work fine and others work wrong.

**Comment by 4w4k3** [comment]
@ilko1810 try https://youtu.be/ifOGkOTS5zk
reclone and follow the steps

**Comment by ilko1810** [comment]
Thank you for your answer. I will try it as soon as possible and ill tell you if it worked :D. Thanks again I appreciate it. 

Have a nice day!


Ilkan Gezer

**Comment by 4w4k3** [comment]
I'll wait your answer, thanks for report error

**Comment by ilko1810** [comment]
Hello 4w4k3,
Its me again sorry that it took me long to feedback on the new way of installation. It worked thank you very much. 

However windows defender detects the keylogger. Is there a way to change that?


Ilkan Gezer

**Comment by 4w4k3** [comment]
Hi @ilko1810 , I can try modify, but its normal AV and Defender detect Bee, he are running in many machines. :d

**Comment by aslami** [comment]
Hi!
It stops installation after the first setup wizard and asks for python. and I recloned and reinstalled several times, but still it has the same error.
Here I attached a screenshot
![screenshot_beelogger](https://cloud.githubusercontent.com/assets/24816479/26386465/ce0537ee-3ffb-11e7-8e7c-93ad934023f7.png)

**Comment by manojsingh7262** [comment]
i also have same problem please reply #4w4k3

**Comment by franklintimoteo** [comment]
Try to install Python 2.7 manually.
https://github.com/4w4k3/BeeLogger/blob/master/python-2.7.12.msi

And later try, 
https://github.com/4w4k3/BeeLogger/blob/master/pywin32-220.win32-py2.7.exe

**Comment by manojsingh7262** [comment]
I already installed Python 2.7 and wine32 manually but same error occurred.
