### ISSUE TITLE
Good Software!

### ISSUE THREAD

**Issue by Virgula0** [4w4k3/BeeLogger#16]
hey guys,
this software is very good, I hope that you will update it continuously... However , the keylogger is good but some important characters are not detected like " or ' 
It would interesting if you could add also other email server to send and receive email because now, it's difficult open a new anonymous account with google!

**Comment by 4w4k3** [comment]
The next version is comming, and will be add these functions.

**Comment by latrellvie2** [comment]
Hi ! I find that BeeLogger isnt practicable.
1. BeeLogger cant be sent through email , it will be detected and exposed as virus !
2. Once you put Beelogger on receivers computer (maybe via usb) it will also get detected in shortest time !

Do you have other experiences , or am I missing something ? Please correct me if i m wrong !   Thank you in advance for reply

**Comment by 4w4k3** [comment]
Probably, email block 'cause are an exe. The most email providers will block it cause them block any .exe, I will check about the 2 topic.

**Comment by SM-Fahim** [comment]
Having the same problem.
I can't send it to anyone,detecting virus.
You said it's because of exe file.
Then how can I send it?

**Comment by Virgula0** [comment]
> Having the same problem.
I can't send it to anyone,detecting virus.
You said it's because of exe file.
Then how can I send it?

Try to zip and send it
