### ISSUE TITLE
Compability Issue

### ISSUE THREAD

**Issue by thisisdipen** [4w4k3/BeeLogger#17]
Does it work with Windows 8.1,10 or any linux OS?

**Comment by thisisdipen** [comment]
Error showed on windows 8.1 system when executed "Cannot Execute K Script"
What does it mean and how can i fix it?

**Comment by 4w4k3** [comment]
Check if dependencies are installed

**Comment by 4w4k3** [comment]
Check if dependencies are installed

**Comment by 4w4k3** [comment]
@thisisdipen try https://youtu.be/ifOGkOTS5zk
reclone and follow the steps
