### ISSUE TITLE
Failed to execute script k

### ISSUE THREAD

**Issue by devil67** [4w4k3/BeeLogger#18]
bug Failed to execute script k
![schermata 2017-04-08 19 01 12](https://cloud.githubusercontent.com/assets/19134092/24830852/134d6d8a-1c8e-11e7-9ef4-ee081a3c987f.png)

**Comment by 4w4k3** [comment]
Check if all deps are installed

**Comment by devil67** [comment]
all deps are installed

**Comment by devil67** [comment]
try to my windows same bug too

**Comment by 4w4k3** [comment]
Wait some moments i'll check it

**Comment by devil67** [comment]
right chech my log or the bug

**Comment by devil67** [comment]
Bee > u
[*] Checking version information..
[*] You are already up to date with git origin master.

**Comment by 4w4k3** [comment]
@devil67 try https://youtu.be/ifOGkOTS5zk
reclone and follow the steps
