### ISSUE TITLE
Failed to execute script k

### ISSUE THREAD

**Issue by thansau239** [4w4k3/BeeLogger#2]
Dear @4w4k3 ,
I have1 issue when run in windows 8.1 "failed to execute script k"
Please help me

**Comment by 4w4k3** [comment]
Hello,
This happen only when you run in Windows 8.1? In others O.S. is OK?

**Comment by thansau239** [comment]
Yes, only in windows 8.1 32bit

**Comment by 4w4k3** [comment]
I will check this, please wait some moments.

**Comment by KurtC0ba1n** [comment]
hi, before, i old to say your software is very nice and user-friendly but i have the same error, i tested it on windows 7 & 10 32bits, i checked the source code of bee.py and some others files and everything seems to be ok, I think it's a bug due to wine's files(or not, i can do some mistakes), you should check them out...

**Comment by 4w4k3** [comment]
Yeah, but works on some systems are working fine, i dont understand what happens

**Comment by 4w4k3** [comment]
@KurtC0ba1n  Do you've tested it in 64 systems?

**Comment by KurtC0ba1n** [comment]
sure, i tested on windows 10 64bits,... same issue

**Comment by KikePuma** [comment]
Tested on Windows 7 Home Basic SP1 64 bits and a I get the same issue: **Failed to execute script k**
It is an awesome program, please fix it @4w4k3. Don't let it fall in the darkness :crying_cat_face:

**Comment by 4w4k3** [comment]
Try clone and run again boys, sorry for this. =D

**Comment by 4w4k3** [comment]
@thansau239 @KurtC0ba1n @KikePuma

**Comment by KurtC0ba1n** [comment]
Is update.py works?

**Comment by KurtC0ba1n** [comment]
Or should i clone and run again?

**Comment by 4w4k3** [comment]
Clone and run it. The error have are in install process.

**Comment by KikePuma** [comment]
I clone it again and run it, but the **k error** is not solved. :(

**Comment by KikePuma** [comment]
The error is not solved @4w4k3, please, don't close the issue.

**Comment by 4w4k3** [comment]
@KikePuma Verify if keylogger are running execute 'msconfig' and search for "adobeflashplayer.exe" if are running, close it and try run your new exe

**Comment by 4w4k3** [comment]
Now its fixed :D remeber of stop and run new if you will test with another email. @KikePuma @KurtC0ba1n @thansau239

**Comment by dukeacejosh** [comment]
This is only working in my current pc. Not in the entire world. Anything I made a mistake on making a beelogger? Any suggestion? thanks

**Comment by shane2483** [comment]
Same issue for me. Ive deleted and cloned again. Same issue
