### ISSUE TITLE
Maybe just my mistake...

### ISSUE THREAD

**Issue by Anon-NM** [4w4k3/BeeLogger#21]
When inputing "smtp.gmail.com:PORT" as server and port necessary it gives the error:
" [!] Please use a valid smtp server "
may just be a format issue on my end, any help?

**Comment by 4w4k3** [comment]
Hello,
First you need put server "smtp.gmail.com" and after he will ask the port and you put the port "587". So must be like this:
Put Server: smpt.xxx.com
Put Port:  XXX

**Comment by MrElMay** [comment]
hy
i am form indonesia
i am just new user
i this error 

Bee > 3
You can see a list with servers and ports in SERVERS.txt on BeeLogger folder.
Type email server (ex: 'smtp.gmail.com'): smtp.gmail.com
 [!] Please use a valid smtp server.
You can see a list with servers and ports in SERVERS.txt on BeeLogger folder.
Type email server (ex: 'smtp.gmail.com'): 



can u help me ?

**Comment by drshell60** [comment]
Hello 
same problem , i type it correct and try to change everything but still 
" [!] Please use a valid smtp server "

**Comment by 4w4k3** [comment]
Try now guys, i fixed it, reclone please

**Comment by 4w4k3** [comment]
@drshell60 @MrElMay @Anon-NM

**Comment by drshell60** [comment]
im trying to install.sh it stock on this step , i cant press next or change anything 
![1s](https://cloud.githubusercontent.com/assets/27744465/25155665/4908e19c-2464-11e7-9ece-5a36d8ba1401.jpg)

**Comment by 4w4k3** [comment]
Hey @drshell60 What's your wine version?
Just type "wine --version"

**Comment by Bakr200** [comment]
Could you please explain more
it not worked with me when I type  my email !!
please help!!

**Comment by 4w4k3** [comment]
@Bakr200 do you  have input smtp server and port?

**Comment by Bakr200** [comment]
I think yea but wrong 
just tell me what must i do when he ask me my email !!

**Comment by Bakr200** [comment]
![ssa](https://cloud.githubusercontent.com/assets/27789103/25249737/3691478c-2628-11e7-8c14-3b4be7a270f5.png)

**Comment by Bakr200** [comment]
![screenshot from 2017-04-21 00-49-27](https://cloud.githubusercontent.com/assets/27789103/25250952/e1d10d68-262c-11e7-911d-6cb021ed19b0.png)

**Comment by drshell60** [comment]
You need to run updater.py to take new update bakr200

**Comment by Bakr200** [comment]
![sddddddddddddd](https://cloud.githubusercontent.com/assets/27789103/25257455/6d233fb0-264d-11e7-8cd8-2cbe8371d8a2.png)

**Comment by Bakr200** [comment]
still not working !!!

**Comment by 4w4k3** [comment]
Reclone now please

**Comment by Bakr200** [comment]
all the tools?

**Comment by 4w4k3** [comment]
Only BeeLogger

**Comment by Bakr200** [comment]
Thanx ...           worked 

thanx

**Comment by Bakr200** [comment]
Can I put this beelogger file in mobile and spy ?

**Comment by 4w4k3** [comment]
It just work for windows. Maybe in future can be released a mobile keylogger. Its a good idea. :D

**Comment by Anon-NM** [comment]
thank you I got it working.
