### ISSUE TITLE
not receiving logs + weird typing glitch

### ISSUE THREAD

**Issue by Andkoo** [4w4k3/BeeLogger#23]
I have built fake adobe updater file in my virtualbox based Kali Linux and transfered it into my host Windows 10 machine. Ran it, the process of Adobe Update Manager (which is disguised BeeLogger) opened in my task manager, but I don't receive any logs to my email. I used smtp.gmail.com, port 587, correct email and correct password, but yet still I don't receive any logs. Also...that would maybe do for a separate issue, here in Slovakia we have some characters like ď, š, ľ and you write them by using key combination of shift + =, releasing this combination and pressing a letter on your keyboard, which you want to assign that lil' special thing onto...you know like that little apostrophy-like thingy on ď. The problem is that when you press shift + = combo, it automatically writes ˇˇ and doesn't wait for the letter to be pressed. And that is definitely detectable by victim.

**Comment by 4w4k3** [comment]
Well, actually BeeLogger just have official support for latim languages, i've tried add support to languages like russian, they ask me a lot, but this time i can't add support to non latim, missing time enough. BeeLogger now isn't FUD, 'cause so much people have used it and heuristic detected this fact, but he's dedicated to pentest and in some scenarios not require bypass AV. I think that it you have meant with "And that is definitely detectable by victim." is don't bypass AV anymore.

**Comment by Andkoo** [comment]
It doesn't pass even windows deffender but ppl are stupid enough to click "run anyway" if you tell them to. Great tool for pentesting, but not receiving logs is a crucial problem to me. And as a developer who currently tries to pentest his own security I kinda need this.

**Comment by 4w4k3** [comment]
The trouble is your NON LATIN language :( 
And, bypass AV and bypass UAC are things different.
