### ISSUE TITLE
Not working!!

### ISSUE THREAD

**Issue by Nalaa99** [4w4k3/BeeLogger#25]
When I put the Beelogger file and clicked on it in windows 7 64bit and typed some words but, nothing!
I did not receive anything to my mail
Indeed, I checked when I inter my mail, pass, smtp and the port!

please help me!

**Comment by 4w4k3** [comment]
unfortunally the error was in custom smtp method, so use the standard with GMAIL, it are fixed now. Reclone and happy pentest.
