### ISSUE TITLE
Quick Questions 

### ISSUE THREAD

**Issue by lcookiemonsterz** [4w4k3/BeeLogger#26]
Really good program, good job 4w4k3. I really like it, but I had a few quick questions 

1. If I were to delete the file I made (.exe) will it still work (this includes emptying the recycle bin) or do I have to go to maconfig and disable it

2. Is there a way I can delete the <spacebar> <backspace> in the email, or maybe that can be a new update? 

3. What phishing tolls were included? I didn't see any in the options.

Thank you, and nice program once again (really quick you might wanna add snapshots?)

**Comment by lcookiemonsterz** [comment]
Whoops let me remake 2

2) is there a way I can delete the "spacebar" or "backspace"

**Comment by 4w4k3** [comment]
Hi  @lcookiemonsterz.
1- You need to remove file on C:\Users\Public\Intel
2- I'll see in next update.
3- the fileformat is the phish

**Comment by 4w4k3** [comment]
And will add the snapshots with next version :D

**Comment by TheBlackBaken** [comment]
Hello,

Firstable, The program is great.

The only drawback of this keylogger is the size of the executable file, about 6 MB !!, mostly overlay. So i was enable to  reduce  it size by using UPX or any other executable compressor.

I also tried to remove the overlay and i got an exectable of about 100 KB, but in this case the keylogger is no more working.

Do you have any other ideas for reducing the size of the executable file. 

Sorry for my english and Thank you in advance.

**Comment by lcookiemonsterz** [comment]
Alright thanks again, one more thing 

Does the keylogger work on multiple users on the same pc 

Ex. I have a pc with users 1, 2, and 3. If I put the logger on 1 and he executed it, will I get logs from users 2 and 3 also? And does the the logger activate once they signed in or once the computer turns on (right now I'm assuming it starts when Windows starts without pitting it in the startup folder) Just for clarification

**Comment by 4w4k3** [comment]
Hi @lcookiemonsterz , 
The bee exe don't stay on startup folder, he stay on registry.
