### ISSUE TITLE
Executable size is too large.

### ISSUE THREAD

**Issue by TheBlackBaken** [4w4k3/BeeLogger#27]
Hello,

Firstable, The program is great.

The only drawback of this keylogger is the size of the executable file, about 6 MB !!, mostly overlay. So i was enable to reduce it size by using UPX or any other executable compressor.

I also tried to remove the overlay and i got an exectable of about 100 KB, but in this case the keylogger is no more working.

Do you have any other ideas for reducing the size of the executable file.

Sorry for my english and Thank you in advance.

**Comment by 4w4k3** [comment]
Hi,
You need compile manually on windows with your custom configurations or you can rewrite he in another language.

**Comment by 4w4k3** [comment]
@TheBlackBaken try compile with py2exe, but its easy to reverse.(rePy2exe)

**Comment by TheBlackBaken** [comment]
Hi and thank you for answers,
I compiled the program under windows but the size of the executable is still important (3,5 MB).
Concerning py2exe, i think it's a bad idea for me.
Now i'm going to try to rewrite the code by using C or C++ but it can take time.

**Comment by 4w4k3** [comment]
@TheBlackBaken Fine, tell me when its done :D
