### ISSUE TITLE
Can't install Python on wine.

### ISSUE THREAD

**Issue by RaytjeKn** [4w4k3/BeeLogger#29]
When I am at the installation of Python for windows, I am not able to click next somehow.

**Comment by RaytjeKn** [comment]
Also when I try to install it myself, it says that I don't have wine32 installed. So when I run apt-get install wine32 it says: Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package wine32 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'wine32' has no installation candidate

**Comment by 4w4k3** [comment]
Try, apt-get install wine -y

**Comment by RaytjeKn** [comment]
No this did not work. You may want to know this, when I run install.sh, it says: "Package wine32 is not available, but is referred to by another package. This may mean that the package is missing, has been obsolete, or is only available from another source.
E: Package 'wine33' has no installation candidate it looks like wine32 is missing, you should install it. As root, please execute "apt-get install wine32""


I already tried running the command, but it gave me the same error with no installation candidate.

**Comment by 4w4k3** [comment]
Ignore this step and only install wine

**Comment by zx0** [comment]
I have they same problem "apt-get install wine32""

**Comment by adalenv** [comment]
sudo dpkg --add-architecture i386
sudo apt-get update 
sudo apt-get install wine32

**Comment by 4w4k3** [comment]
Please clone now and install again
