### ISSUE TITLE
I managed the whole process, but in windows 7 home premium, the file can not be executed, can do everything, 

### ISSUE THREAD

**Issue by Guillerbr** [4w4k3/BeeLogger#33]
I managed the whole process, but on my windows 7 home premium, the file can not be executed, can it work on which windows victim?
What windows systems are supported?

The error I have while executing is:
Windows can not access the specified device, path or file. You may not have the appropriate permissions to access the item.

Even running as administrator and trying to open with old versions did not work on this pc victim win 7 home premium 2009.

I thank you for your program. It is incredible.
thank you

**Comment by 4w4k3** [comment]
@Guillerbr just are working in >= Win7
