### ISSUE TITLE
mail is not recieved.? what the isssue? 

### ISSUE THREAD

**Issue by libra77** [4w4k3/BeeLogger#34]
i have installed exe. in my win 8.. but i havent received any emails..i have given my GMAIL accout credentials

**Comment by 4w4k3** [comment]
Check if you have enabled the less secure apps in your gamil

**Comment by libra77** [comment]
yes i have enabled that

**Comment by 4w4k3** [comment]
Do you have runned bee and it don't show some error?

**Comment by BoneFly** [comment]
I have the same problem, Bee don't show any error.

**Comment by sameernerd** [comment]
Is your issue resolved?

**Comment by haxerx** [comment]
sir plz help ,  beelogger is no send any mail me when i run application { beeLogger} on windows 7. 
{ use os windows7- vm virtualbox-linux64      / less is on / use gmail

**Comment by haxerx** [comment]
help me

**Comment by sameernerd** [comment]
I am also facing the same problem brother.

**Comment by haxerx** [comment]
sir plz help , beelogger is no send any mail me when i run application { beeLogger} on windows 7.
{ use os windows7- vm virtualbox-linux64 / less is on / use gmail
PLZ HELP
