### ISSUE TITLE
Help plz

### ISSUE THREAD

**Issue by ComBorgDev** [4w4k3/BeeLogger#4]
I am on the last version of kali linux and i have this error:
I have an error in the python installation with wine.

These info above are correct? (y/n) :y
wine: cannot find '/root/.wine/drive_c/Python27/python.exe'
Traceback (most recent call last):
  File "bee.py", line 184, in <module>
    main()
  File "bee.py", line 157, in main
    os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory

**Comment by 4w4k3** [comment]
Try type: "sudo rm -Rf .OK" on umbrella dir and try run again reinstalling deps.. What your O.S.?

**Comment by 4w4k3** [comment]
I think that you have achieved. :)
