### ISSUE TITLE
Need Help!! BeeLogger | wine: cannot find '/root/.wine/drive_c/Python27/python.exe'

### ISSUE THREAD

**Issue by khanfurman** [4w4k3/BeeLogger#5]
hese info above are correct? (y/n) :y
wine: cannot find '/root/.wine/drive_c/Python27/python.exe'
Traceback (most recent call last):
  File "./bee.py", line 210, in <module>
    main()
  File "./bee.py", line 160, in main
    os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory

**Comment by 4w4k3** [comment]
Problem with wine... whats your O.S.?

**Comment by 4w4k3** [comment]
Try install python on wine manually.

**Comment by jojodipa1** [comment]
same prb and i hv installed wine manually but didnt work ! :/

**Comment by jojodipa1** [comment]
pls anyhelp !!
![screenshot from 2017-05-09 11-46-33](https://cloud.githubusercontent.com/assets/28510360/25859318/292764c2-34ac-11e7-88b9-3992fcf88191.png)

**Comment by 4w4k3** [comment]
Don't show your creds!
Try "./install.sh "
Can delay one time to install all things

**Comment by jojodipa1** [comment]
its oky abt creds lol it was wrong anyway hhhhhh and scammers will do nothing with me bc im not that important like wt they did with u 
and actually i tried and it shows me this one 
![screenshot from 2017-05-09 14-06-11](https://cloud.githubusercontent.com/assets/28510360/25860155/a7d5d6b2-34ae-11e7-9b2d-da6ab56527c2.png)
![screenshot from 2017-05-09 13-43-24](https://cloud.githubusercontent.com/assets/28510360/25860163/b0230be6-34ae-11e7-8668-32ff82687fd0.png)

**Comment by 4w4k3** [comment]
Kali?

**Comment by jojodipa1** [comment]
yep kali linux 
![screenshot from 2017-05-09 17-10-47](https://cloud.githubusercontent.com/assets/28510360/25860759/95fb2e9a-34b0-11e7-9385-fe74bb1f59d6.png)

**Comment by 4w4k3** [comment]
Try restart and install again, can be a problem with add arch 86

**Comment by jojodipa1** [comment]
restart my computer and install again ?

**Comment by jojodipa1** [comment]
i did and still the same prb says : python version 2.7 required which is not found in the registery 
![screenshot from 2017-05-09 14-06-11](https://cloud.githubusercontent.com/assets/28510360/25861889/21968604-34b4-11e7-8585-d93a0c52e47c.png)

**Comment by madman0010** [comment]
The same as mine. please anyone help....

**Comment by DanyPaisa** [comment]
try to execute all as sudo beelogger search the binary on root

**Comment by ubaidahmad007** [comment]
same problem please anyone helppppppppp

**Comment by im-n00b** [comment]
my trooble same like @jojodipa1 ,im using kali linux ,please sir @4w4k3  how to fixed

**Comment by ghost** [comment]
any solution for this problem ??? please help

**Comment by Linuxhack007** [comment]
4w4k3 you r awesome i just entered. /install.sh and problems was solved. Thank you so much. Broh. 😇😇😇😇

**Comment by krampus0101** [comment]
it doesn't works. gmail detect the virus. can't add this like a attachment :(

**Comment by slaehz** [comment]
solition 
install  in wine whith windows7 not xp
![screenshot from 2018-03-02 21-45-26](https://user-images.githubusercontent.com/37002179/36921269-fb015dd0-1e63-11e8-9aab-29ebe9e65a74.png)

**Comment by macgiversalman** [comment]
[/home/macgiver/Pictures/Screenshot from 2019-09-28 04-53-57.png](url)

**Comment by macgiversalman** [comment]
https://drive.google.com/file/d/1HR3mEba8yHHS17Kb8iDg1R9k-LsE2dp-/view?usp=sharing

download and install wine from here -- try fix problem :-)

**Comment by Hacker441** [comment]
Not working

**Comment by Linuxhack007** [comment]
google it bro its removed maybe

**Comment by mistemoni** [comment]
@ubaidahmad007  did you get it

**Comment by el-laco** [comment]
saaaame here

**Comment by Waqarhyder** [comment]
wine: created the configuration directory '/root/.wine' wine: cannot find '/root/.wine/drive_c/python27/python.exe' traceback (most recent call last): file "bee.py", line 161, in <module> main() file "bee.py", line 97, in main os.rename('dist/k.exe', 'dist/' + name) oserror: [errno 2] no such file or directory
