### ISSUE TITLE
error :(

### ISSUE THREAD

**Issue by Doutianbao** [4w4k3/BeeLogger#7]
C:\Python27\python.exe: can't open file '/root/.wine/drive_c/Python27/Scripts/pyinstaller-script.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "bee.py", line 184, in <module>
    main()
  File "bee.py", line 139, in main
    os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory

**Comment by 4w4k3** [comment]
What your O.S.?

**Comment by Doutianbao** [comment]
Kali rolling

2017年3月16日 上午11:44，"Alisson Moretto" <notifications@github.com>写道：

**Comment by 4w4k3** [comment]
Try reclone and run again

**Comment by Doutianbao** [comment]
Yes, I have done that way several times.

**Comment by 4w4k3** [comment]
@Doutianbao seem that pyinstaller isn't installed, i will check some way to fix the errors with WINE

**Comment by 4w4k3** [comment]
Try now @Doutianbao

**Comment by tacodluver** [comment]
Mine comes up like that too or like this /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'bee.py': [Errno 2] No such file or directory 

How can I fix this?

**Comment by alokblackhat** [comment]
C:\Python27\python.exe: can't open file '/root/.wine/drive_c/Python27/Scripts/pyinstaller-script.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "bee.py", line 161, in <module>
    main()
  File "bee.py", line 134, in main
    os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory






HOW TO FIX?

**Comment by hackerfk7** [comment]
File "bee.py", line 161, in
main()
File "bee.py", line 134, in main
os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory

How to fix it  :(
