### ISSUE TITLE
dected as a virus

### ISSUE THREAD

**Issue by nirajmaharz** [4w4k3/BeeLogger#75]
doesn't work detected by windows defender as a virus

**Comment by quantumcore** [comment]
If you selected the Blank Executable option it is Obvious it would be detected as Virus.

**Comment by nirajmaharz** [comment]
how can we make it undected?

**Comment by quantumcore** [comment]
Try to Select the Other options available, Such as Fake Document or Adobe Flash Player. The Black Executable which is logging Keystrokes will 100% get detected.

If the Problem persists, Crypt it.

**Comment by usama7628674** [comment]
@fastisbac @nirajmaharz It worked uptil windows 10 1709 but detected by win defender in 1803.

**Comment by Mikewins1** [comment]
I have used every option and crypted it and it is detected everytime.  Will not run on Windows unless you turn off AV
