### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ashold7** [4w4k3/BeeLogger#8]
I always get this error, though python.exe is in this location and i installed it properly

wine: cannot find '/root/.wine/drive_c/Python27/python.exe'
Traceback (most recent call last):
  File "bee.py", line 184, in <module>
    main()
  File "bee.py", line 130, in main
    os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory

**Comment by 4w4k3** [comment]
Do you have installed dependencies correct without cancel? seem that python isn't installed.

**Comment by 4w4k3** [comment]
@ashold7

**Comment by 4w4k3** [comment]
Try now
