### ISSUE TITLE
No dependencies to install. No python 2.7 issue (probably)

### ISSUE THREAD

**Issue by sisilana** [4w4k3/BeeLogger#9]
OS Kali Linux 2016.2
on both (BeeLogger and Umbrella) there is a problem showed as:

_wine: cannot find '/root/.wine/drive_c/Python27/python.exe'
Traceback (most recent call last):
  File "./bee.py", line 184, in <module>
    main()
  File "./bee.py", line 139, in main
    os.rename('dist/k.exe', 'dist/' + name)
OSError: [Errno 2] No such file or directory_

I tried many times to install/reinstall. As I found I have Python 3.4 sucessfully installed in .wine with VeilEvasion which makes the dependencies install automatically. On start of Umbrella and BeeLogger after selection of dependencies installation nothing happens. What to do? I really tried before asking.

**Comment by 4w4k3** [comment]
@sisilana BeeLogger use Python 2.7 not 3.4, do you have installed dependencies correct without cancel ?

**Comment by 4w4k3** [comment]
Try reclone now i think that are fixed.
